// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class SteppingGooglePlayServiceResources
{
        public const string achievement_250_steps = "CgkIp8GGtu8FEAIQBQ"; // <GPGSID>
        public const string achievement_250_cubes = "CgkIp8GGtu8FEAIQGQ"; // <GPGSID>
        public const string achievement_500_games = "CgkIp8GGtu8FEAIQEg"; // <GPGSID>
        public const string achievement_750_cubes = "CgkIp8GGtu8FEAIQGw"; // <GPGSID>
        public const string achievement_500_double_jump = "CgkIp8GGtu8FEAIQDQ"; // <GPGSID>
        public const string achievement_750_total_steps = "CgkIp8GGtu8FEAIQIw"; // <GPGSID>
        public const string achievement_5000_total_steps = "CgkIp8GGtu8FEAIQJg"; // <GPGSID>
        public const string achievement_25_steps = "CgkIp8GGtu8FEAIQAQ"; // <GPGSID>
        public const string achievement_100_steps = "CgkIp8GGtu8FEAIQBA"; // <GPGSID>
        public const string achievement_4000_total_steps = "CgkIp8GGtu8FEAIQKA"; // <GPGSID>
        public const string achievement_100_cubes = "CgkIp8GGtu8FEAIQGA"; // <GPGSID>
        public const string achievement_3000_total_steps = "CgkIp8GGtu8FEAIQJw"; // <GPGSID>
        public const string achievement_80_double_jump = "CgkIp8GGtu8FEAIQCg"; // <GPGSID>
        public const string achievement_300_total_steps = "CgkIp8GGtu8FEAIQIA"; // <GPGSID>
        public const string achievement_75_steps = "CgkIp8GGtu8FEAIQAw"; // <GPGSID>
        public const string achievement_1000_games = "CgkIp8GGtu8FEAIQFA"; // <GPGSID>
        public const string achievement_75_cubes = "CgkIp8GGtu8FEAIQFw"; // <GPGSID>
        public const string achievement_40_double_jump = "CgkIp8GGtu8FEAIQCA"; // <GPGSID>
        public const string achievement_250_double_jump = "CgkIp8GGtu8FEAIQDA"; // <GPGSID>
        public const string achievement_100_total_steps = "CgkIp8GGtu8FEAIQHg"; // <GPGSID>
        public const string achievement_300_games = "CgkIp8GGtu8FEAIQEA"; // <GPGSID>
        public const string achievement_200_games = "CgkIp8GGtu8FEAIQDw"; // <GPGSID>
        public const string achievement_60_double_jump = "CgkIp8GGtu8FEAIQCQ"; // <GPGSID>
        public const string achievement_25_cubes = "CgkIp8GGtu8FEAIQFQ"; // <GPGSID>
        public const string achievement_750_games = "CgkIp8GGtu8FEAIQEw"; // <GPGSID>
        public const string achievement_50_steps = "CgkIp8GGtu8FEAIQAg"; // <GPGSID>
        public const string achievement_50_cubes = "CgkIp8GGtu8FEAIQFg"; // <GPGSID>
        public const string achievement_10000_total_steps = "CgkIp8GGtu8FEAIQKQ"; // <GPGSID>
        public const string achievement_500_steps = "CgkIp8GGtu8FEAIQBg"; // <GPGSID>
        public const string achievement_500_cubes = "CgkIp8GGtu8FEAIQGg"; // <GPGSID>
        public const string achievement_100_games = "CgkIp8GGtu8FEAIQDg"; // <GPGSID>
        public const string achievement_500_total_steps = "CgkIp8GGtu8FEAIQIg"; // <GPGSID>
        public const string leaderboard_best_steps = "CgkIp8GGtu8FEAIQHQ"; // <GPGSID>
        public const string achievement_20_double_jump = "CgkIp8GGtu8FEAIQBw"; // <GPGSID>
        public const string achievement_200_total_steps = "CgkIp8GGtu8FEAIQHw"; // <GPGSID>
        public const string achievement_2000_total_steps = "CgkIp8GGtu8FEAIQJQ"; // <GPGSID>
        public const string achievement_400_games = "CgkIp8GGtu8FEAIQEQ"; // <GPGSID>
        public const string achievement_100_double_jump = "CgkIp8GGtu8FEAIQCw"; // <GPGSID>
        public const string achievement_1000_cubes = "CgkIp8GGtu8FEAIQHA"; // <GPGSID>
        public const string achievement_400_total_steps = "CgkIp8GGtu8FEAIQIQ"; // <GPGSID>
        public const string achievement_1000_total_steps = "CgkIp8GGtu8FEAIQJA"; // <GPGSID>

}

